//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class tblCustomer
    {
        public tblCustomer()
        {
            this.tblComplaints = new HashSet<tblComplaint>();
        }

        public int CustomerId { get; set; }
        [Required(ErrorMessage = "Please Enter First Name.")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Please enter a valid Name.")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Please Enter Last Name.")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Please enter a valid Name.")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Please enter account number.")]
        [RegularExpression(@"^\d{10,20}$", ErrorMessage = "Account number must contain 10 - 20 digits.")]
        public string AccountNumber { get; set; }
        [Required(ErrorMessage = "Please enter branch.")]
        [RegularExpression(@"^[a-zA-Z ]+$", ErrorMessage = "Branch name should contain alphabets.")]
        public string Branch { get; set; }
        [Required(ErrorMessage = "Please enter address.")]
        public string Addr { get; set; }
        [Required(ErrorMessage = "Please enter Email.")]
        [RegularExpression(@"^([a-z0-9_\-\.]+)@((\[[0-9]{1,3}" + @"\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\" + @".)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Please enter a valid Email Address.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter Password.")]
        [DataType(DataType.Password)]
        [RegularExpression(@"((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*_]).{6,20})", ErrorMessage = "Password should be 6-20 characters with at least one upper case letter, one lower case letter, one special character and a number.")]
        public string Pssd { get; set; }
        [Required(ErrorMessage = "Please enter Phone Number.")]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "Phone number must contain 10 digits.")]
        public string Phone { get; set; }
        [NotMapped]
        [Required(ErrorMessage = "Please enter Confirm Password.")]
        [Compare(@"Pssd", ErrorMessage = "Password and Confirm Password should match.")]
        [DataType(DataType.Password)]
        public string ConPssd { get; set; }
        public string SecurityQuestion { get; set; }
        [Required(ErrorMessage = "Please enter Security Answer")]
        [RegularExpression(@"^[a-zA-Z ]+$", ErrorMessage = "Answer should contain alphabets.")]
        public string SecurityAnswer { get; set; }
    
        public virtual ICollection<tblComplaint> tblComplaints { get; set; }
    }
}
